#!/usr/bin/env zsh
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    makehpp                                            :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mli <mli@student.42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/07/23 21:53:24 by mli               #+#    #+#              #
#    Updated: 2021/03/30 14:00:58 by mli              ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

if [ -z "$1" ]; then
	echo "Usage:\n\tmakehpp <filename>";
	exit;
fi

stars="************************************************************************"
uppercase=$(echo "$1" | awk '{ print toupper($0) }')
hpp_file=${1}.hpp
protection="${uppercase}_HPP"

printf >> $hpp_file \
"#ifndef ${protection}
# define ${protection}

# include <iostream>
# include <string>

#endif // %.*s ${protection} end //\n" $((80 - 18 - ${#protection})) "$stars"
