#!/usr/bin/env zsh
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    never_went_here                                    :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mli <mli@student.42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/05/09 15:48:17 by mli               #+#    #+#              #
#    Updated: 2020/11/11 12:47:08 by mli              ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

function source_rc () {
	for rcfile in $@; do
		echo "source ${DOTFILES}/$rcfile" >> ~/.$rcfile
	done
}

function lnrc () {
	for rcfile in $@; do
		ln -s ${DOTFILES}/$rcfile ~/.$rcfile
	done
}

source_rc zshrc bashrc vimrc
lnrc valgrindrc pylintrc
